name: Desplegar Apache EA2

on:
  workflow_dispatch:

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/apache-ea2:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/apache-ea2:latest

      - name: Desplegar Rolling Update en k3s
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.K3S_SERVER_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EA2_SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/apache-ea2
            cd ~/apache-ea2

            curl -L https://raw.githubusercontent.com/ValentinaAstudillo/SDLC003D-Apache-ValentinaAstudillo/main/k8s/rolling-update.yaml -o rolling-update.yaml

            kubectl apply -f rolling-update.yaml
            kubectl rollout status deployment/duoc-app-deployment
            kubectl get pods
            kubectl get svc
            curl -I http://localhost:30101